Override strict_variable option using config
zendframework/zend-expressive-twigrenderer pull request #56
Opened 2019-02-16 13:07 UTC by bernard-ng

override the mode '**strict_variables**' in the **TwigEnvironmentFactory** via the configuration

2019-02-18 07:42 UTC, michalbundyra requested changes
LGTM but we need update also README.md, please

2019-02-18 08:00 UTC, froschdesign commented
> …we need update also README.md

The readme file is maybe correct here, but the documentation is always more important!

2019-03-02 21:20 UTC, bernard-ng commented
still waiting for a merge

2019-03-03 07:10 UTC, geerteltink approved these changes

2019-03-17 09:53 UTC, michalbundyra approved these changes
@bernard-ng The PR looks good for me, but as @froschdesign we need also updated documentation, please see: https://github.com/zendframework/zend-expressive/blob/master/docs/book/v3/features/template/twig.md
So we need another PR to that library with changes in that file.

2019-03-17 09:53 UTC, webimpress commented on README.md
> +    'strict_variables' => false // Ignore invalid variables
trailing comma, please

2019-03-18 20:30 UTC, closed without merging